export interface BibleBookMeta {
  abbrev: string;
  name: string;
  testament: "AT" | "NT";
  chapterCount: number;
}

export const BIBLE_BOOKS: BibleBookMeta[] = [
  // Antigo Testamento
  { abbrev: "gn",  name: "Gênesis",           testament: "AT", chapterCount: 50  },
  { abbrev: "ex",  name: "Êxodo",              testament: "AT", chapterCount: 40  },
  { abbrev: "lv",  name: "Levítico",           testament: "AT", chapterCount: 27  },
  { abbrev: "nm",  name: "Números",            testament: "AT", chapterCount: 36  },
  { abbrev: "dt",  name: "Deuteronômio",       testament: "AT", chapterCount: 34  },
  { abbrev: "js",  name: "Josué",              testament: "AT", chapterCount: 24  },
  { abbrev: "jz",  name: "Juízes",             testament: "AT", chapterCount: 21  },
  { abbrev: "rt",  name: "Rute",               testament: "AT", chapterCount: 4   },
  { abbrev: "1sm", name: "1 Samuel",           testament: "AT", chapterCount: 31  },
  { abbrev: "2sm", name: "2 Samuel",           testament: "AT", chapterCount: 24  },
  { abbrev: "1rs", name: "1 Reis",             testament: "AT", chapterCount: 22  },
  { abbrev: "2rs", name: "2 Reis",             testament: "AT", chapterCount: 25  },
  { abbrev: "1cr", name: "1 Crônicas",         testament: "AT", chapterCount: 29  },
  { abbrev: "2cr", name: "2 Crônicas",         testament: "AT", chapterCount: 36  },
  { abbrev: "ed",  name: "Esdras",             testament: "AT", chapterCount: 10  },
  { abbrev: "ne",  name: "Neemias",            testament: "AT", chapterCount: 13  },
  { abbrev: "et",  name: "Ester",              testament: "AT", chapterCount: 10  },
  { abbrev: "jó",  name: "Jó",                 testament: "AT", chapterCount: 42  },
  { abbrev: "sl",  name: "Salmos",             testament: "AT", chapterCount: 150 },
  { abbrev: "pv",  name: "Provérbios",         testament: "AT", chapterCount: 31  },
  { abbrev: "ec",  name: "Eclesiastes",        testament: "AT", chapterCount: 12  },
  { abbrev: "ct",  name: "Cânticos",           testament: "AT", chapterCount: 8   },
  { abbrev: "is",  name: "Isaías",             testament: "AT", chapterCount: 66  },
  { abbrev: "jr",  name: "Jeremias",           testament: "AT", chapterCount: 52  },
  { abbrev: "lm",  name: "Lamentações",        testament: "AT", chapterCount: 5   },
  { abbrev: "ez",  name: "Ezequiel",           testament: "AT", chapterCount: 48  },
  { abbrev: "dn",  name: "Daniel",             testament: "AT", chapterCount: 12  },
  { abbrev: "os",  name: "Oséias",             testament: "AT", chapterCount: 14  },
  { abbrev: "jl",  name: "Joel",               testament: "AT", chapterCount: 3   },
  { abbrev: "am",  name: "Amós",               testament: "AT", chapterCount: 9   },
  { abbrev: "ob",  name: "Obadias",            testament: "AT", chapterCount: 1   },
  { abbrev: "jn",  name: "Jonas",              testament: "AT", chapterCount: 4   },
  { abbrev: "mq",  name: "Miquéias",           testament: "AT", chapterCount: 7   },
  { abbrev: "na",  name: "Naum",               testament: "AT", chapterCount: 3   },
  { abbrev: "hc",  name: "Habacuque",          testament: "AT", chapterCount: 3   },
  { abbrev: "sf",  name: "Sofonias",           testament: "AT", chapterCount: 3   },
  { abbrev: "ag",  name: "Ageu",               testament: "AT", chapterCount: 2   },
  { abbrev: "zc",  name: "Zacarias",           testament: "AT", chapterCount: 14  },
  { abbrev: "ml",  name: "Malaquias",          testament: "AT", chapterCount: 4   },
  // Novo Testamento
  { abbrev: "mt",  name: "Mateus",             testament: "NT", chapterCount: 28  },
  { abbrev: "mc",  name: "Marcos",             testament: "NT", chapterCount: 16  },
  { abbrev: "lc",  name: "Lucas",              testament: "NT", chapterCount: 24  },
  { abbrev: "jo",  name: "João",               testament: "NT", chapterCount: 21  },
  { abbrev: "atos", name: "Atos",               testament: "NT", chapterCount: 28  },
  { abbrev: "rm",  name: "Romanos",            testament: "NT", chapterCount: 16  },
  { abbrev: "1co", name: "1 Coríntios",        testament: "NT", chapterCount: 16  },
  { abbrev: "2co", name: "2 Coríntios",        testament: "NT", chapterCount: 13  },
  { abbrev: "gl",  name: "Gálatas",            testament: "NT", chapterCount: 6   },
  { abbrev: "ef",  name: "Efésios",            testament: "NT", chapterCount: 6   },
  { abbrev: "fp",  name: "Filipenses",         testament: "NT", chapterCount: 4   },
  { abbrev: "cl",  name: "Colossenses",        testament: "NT", chapterCount: 4   },
  { abbrev: "1ts", name: "1 Tessalonicenses",  testament: "NT", chapterCount: 5   },
  { abbrev: "2ts", name: "2 Tessalonicenses",  testament: "NT", chapterCount: 3   },
  { abbrev: "1tm", name: "1 Timóteo",          testament: "NT", chapterCount: 6   },
  { abbrev: "2tm", name: "2 Timóteo",          testament: "NT", chapterCount: 4   },
  { abbrev: "tt",  name: "Tito",               testament: "NT", chapterCount: 3   },
  { abbrev: "fm",  name: "Filemom",            testament: "NT", chapterCount: 1   },
  { abbrev: "hb",  name: "Hebreus",            testament: "NT", chapterCount: 13  },
  { abbrev: "tg",  name: "Tiago",              testament: "NT", chapterCount: 5   },
  { abbrev: "1pe", name: "1 Pedro",            testament: "NT", chapterCount: 5   },
  { abbrev: "2pe", name: "2 Pedro",            testament: "NT", chapterCount: 3   },
  { abbrev: "1jo", name: "1 João",             testament: "NT", chapterCount: 5   },
  { abbrev: "2jo", name: "2 João",             testament: "NT", chapterCount: 1   },
  { abbrev: "3jo", name: "3 João",             testament: "NT", chapterCount: 1   },
  { abbrev: "jd",  name: "Judas",              testament: "NT", chapterCount: 1   },
  { abbrev: "ap",  name: "Apocalipse",         testament: "NT", chapterCount: 22  },
];
